version: '3.7'

services:
  my-study-planner-api:
    container_name: my-study-planner-docker
    build: ./
    command: npm run inspect
    working_dir: /usr/src/my-study-planner-api
    depends_on:
      - database
    ports:
      - '3001:3001'
    volumes:
      - ./:/usr/src/my-study-planner-api
      - /usr/src/my-study-planner-api/node_modules/

  database:
    image: mongo:latest
    ports:
      - '27017:27017'

  redis:
    image: redis
    ports:
      - '6379:6379'
